# Generated by Django 2.2.5 on 2020-12-10 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workcategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Work material',
            },
        ),
        migrations.CreateModel(
            name='WorkSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Work Size',
            },
        ),
        migrations.CreateModel(
            name='WorksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worksTitle', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('year', models.CharField(default='', max_length=4, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='workcategory.WorksCategoryModel')),
                ('material', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work', to='works.WorkMaterial')),
                ('size', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work', to='works.WorkSize')),
            ],
        ),
    ]
